# Generated by Django 4.0.6 on 2022-08-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('job_location', models.CharField(max_length=30)),
                ('employment_type', models.CharField(max_length=30)),
                ('organizaton', models.CharField(max_length=40)),
                ('mandatory_qualification', models.CharField(max_length=40)),
                ('optional_qualification', models.CharField(max_length=40)),
                ('experience', models.IntegerField()),
                ('what_is_expected', models.IntegerField()),
                ('what_we_offer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('notice_period', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('selected', 'selected'), ('rejected', 'rejected')], max_length=20)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.user')),
            ],
        ),
    ]
