# Generated by Django 4.1 on 2022-09-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='what_is_expected',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='what_we_offer',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_brief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to=None),
        ),
    ]
