# Generated by Django 4.0.6 on 2022-08-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_user_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='what_is_expected',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='what_we_offer',
            field=models.CharField(max_length=10),
        ),
    ]
