# Generated by Django 4.0.6 on 2022-08-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('read_item', 'Can read item'),)},
        ),
    ]
