# Generated by Django 4.0.6 on 2022-08-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdescription',
            options={'permissions': (('read_item', 'Can read item'),)},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
    ]
