# Generated by Django 4.0.6 on 2022-08-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_jobdescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='employment_type',
            field=models.CharField(choices=[('Part time', 'part time'), ('Full time', 'full time')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_category',
            field=models.CharField(choices=[('HR', 'HR'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full stack', 'Full stack'), ('Dev Ops', 'Dev Ops'), ('BDE', 'BDE'), ('others', 'others')], max_length=30),
        ),
    ]
