# Generated by Django 4.0.6 on 2022-08-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_alter_jobdescription_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In_progress'), ('selected', 'Selected'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='employment_type',
            field=models.CharField(choices=[('Part time', 'Part-time'), ('Full time', 'Full-time')], max_length=30),
        ),
    ]
